// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var wioApp;

  wioApp = angular.module('wioApp', ['ngResource'], function() {});

  wioApp.config([
    '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
      $routeProvider.when('/', {
        templateUrl: '/static/partials/main.html',
        controller: 'MainCtrl'
      });
      $routeProvider.when('/applied', {
        templateUrl: '/static/partials/applied.html',
        controller: 'AppliedCtrl'
      });
      $routeProvider.when('/confirm_email/:emailHash', {
        templateUrl: '/static/partials/confirm_email.html',
        controller: 'ConfirmCtrl'
      });
      $routeProvider.otherwise({
        redirectTo: '/'
      });
      return $locationProvider.html5Mode(true);
    }
  ]);

  wioApp.config([
    '$httpProvider', function($httpProvider) {
      var $http, interceptor;

      $http = null;
      interceptor = [
        '$q', '$injector', function($q, $injector) {
          var error, success;

          success = function(response) {
            $http = $http || $injector.get('$http');
            if ($http.pendingRequests.length < 1) {
              $('#loadingWidget').hide();
            }
            return response;
          };
          error = function(response) {
            $http = $http || $injector.get('$http');
            if ($http.pendingRequests.length < 1) {
              $('#loadingWidget').hide();
            }
            return $q.reject(response);
          };
          return function(promise) {
            $('#loadingWidget').show();
            return promise.then(success, error);
          };
        }
      ];
      return $httpProvider.responseInterceptors.push(interceptor);
    }
  ]);

  wioApp.controller('MainCtrl', [
    '$scope', function($scope) {
      $scope.applyStatus = 'pre-register';
      return $scope.applyBetaAccount = function() {
        return $scope.applyStatus = 'email';
      };
    }
  ]);

  wioApp.controller('RegisterCtrl', [
    '$scope', '$location', '$http', 'AppliedUser', function($scope, $location, $http, AppliedUser) {
      $scope.validEmail = true;
      return $scope.register = function() {
        var email, postData;

        $scope.validEmail = $scope.regForm['email'].$dirty && $scope.regForm['email'].$valid && !$scope.regForm['email'].$error.email;
        if ($scope.validEmail) {
          $('#registerBtn').attr('disabled', 'disabled');
          email = {
            email: $scope.email
          };
          postData = JSON.stringify(email);
          return $http.post('/register', postData).success(function(data) {
            AppliedUser.set(data);
            return $location.path('/applied');
          });
        }
      };
    }
  ]);

  wioApp.controller('AppliedCtrl', [
    '$scope', 'AppliedUser', function($scope, AppliedUser) {
      return $scope.email = AppliedUser.get();
    }
  ]);

  wioApp.controller('ConfirmCtrl', [
    '$scope', '$http', function($scope, $http) {
      return $http.get('/static/json/wechat_picks.json').success(function(data) {
        $scope.operation = data[0];
        return $scope.product = data[1];
      });
    }
  ]);

  wioApp.directive('uiIf', function() {
    return {
      transclude: 'element',
      priority: 1000,
      terminal: true,
      restrict: 'A',
      compile: function(elem, attrs, transclude) {
        return function(scope, elem, attrs) {
          return scope.$watch(attrs['uiIf'], function(newValue) {
            var childElement, childScope;

            childElement = null;
            childScope = null;
            if (childElement) {
              childElement.remove();
              childElement = void 0;
            }
            if (childScope) {
              childScope.$destroy();
              childScope = void 0;
            }
            if (newValue) {
              childScope = scope.$new();
              return transclude(childScope, function(clone) {
                childElement = clone;
                return elem.after(clone);
              });
            }
          });
        };
      }
    };
  });

  wioApp.service('AppliedUser', function() {
    var appliedUser;

    appliedUser = {};
    return {
      set: function(data) {
        return appliedUser = data;
      },
      get: function() {
        return appliedUser;
      }
    };
  });

}).call(this);
